apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: broken-link
message: "App for testing docs.csc.fi and report broken links"
metadata:
  annotations:
    description: "Check links broken"
  name: broken-link
parameters:
- name: NAMESPACE
  description: Specify your namespace where you will deploy the template
  required: true

- name: GITHUB_URL
  description: URL of the GitHub repo where the app is located
  required: true
  value: https://github.com/CSCfi/broken-link-s2i.git

- name: GITHUB_BRANCH
  description: Branch used in the GitHub repo
  required: true
  value: main

- name: EMAIL_RECIPIENT
  description: Email address of the recipient
  required: true

- name: OUTPUT_MARKDOWN
  description: Send email attachment in Markdown format
  value: false
  required: false

objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: broken-link
    name: broken-link
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: broken-link:latest
    source:
      git:
        ref: ${GITHUB_BRANCH}
        uri: ${GITHUB_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: EMAIL_RECIPIENT
          value: ${EMAIL_RECIPIENT}
        - name: OUTPUT_MARKDOWN
          value: ${OUTPUT_MARKDOWN}
        from:
          kind: ImageStreamTag
          name: python:3.9-ubi8
          namespace: openshift
      type: Source
    triggers:
      - type: ImageChange
      - type: ConfigChange

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: broken-link
    name: broken-link
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: true

- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: broken-link
    namespace: ${NAMESPACE}
  spec:
    schedule: '0 3 2 * *'
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: broken-link
                image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/broken-link:latest
            restartPolicy: OnFailure
